language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false
dist: xenial
# command to install dependencies
install: "pip install tox-travis"
# command to run tests
script: tox
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net##legoktm"
    skip_join: true
    on_success: change
    on_failure: always
